config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from rentals.sitemaps import HouseSitemap
from services.sitemaps import ServiceSitemap
from django.views.generic import TemplateView


sitemaps = {
    'houses': HouseSitemap,
    'services': ServiceSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('finance/',include('finances.urls')),
    path('rentals/',include('rentals.urls')),
    path('services/',include('services.urls')),
    path('rentanything/', include('rentanything.urls')),
    path('buyandsell/', include('buyandsell.urls')),
    path('deliveranything/', include('deliveranything.urls')),
    path('businesses/', include('businesses.urls')),
    path('faq/',include('faq.urls')),
    path('',include('agreements.urls')),
    path('membership/',include('memberships.urls')),
    path('dashboard/',include('dashboards.urls')),
    path('robots.txt', include('robots.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboards/urls.py
from django.urls import path
from . import views as dashboard_views



urlpatterns = [

    #Landlord
    path('landlord/',  dashboard_views.dashboard_landlord, name='dashboard'),
    path('landlord/schedule_for_viewing' , dashboard_views.dashboard_landlord, name='landlord_schedule_for_viewing'),

    path('landlord/tenants' , dashboard_views.dashboard_landlord, name='landlord_tenants'),
    path('landlord/tenants/verification' , dashboard_views.dashboard_landlord, name='landlord_tenants_verification'),

    path('landlord/applications' , dashboard_views.dashboard_landlord, name='landlord_applications'),
    path('landlord/applications/comparison' , dashboard_views.dashboard_landlord, name='landlord_applications_comparison'),

    path('landlord/rental_insurance' , dashboard_views.dashboard_landlord, name='landlord_rental_insurance'),
    path('landlord/services' , dashboard_views.dashboard_landlord, name='landlord_services'),

    #Tenant
    path('tenant/' , dashboard_views.dashboard_tenant, name='dashboard_tenant'),
    path('tenant/applications', dashboard_views.dashboard_tenant, name='tenant_applications'),
    path('tenant/schedule_for_viewing', dashboard_views.dashboard_tenant, name='tenant_schedule_for_viewing'),
    path('tenant/rental_insurance', dashboard_views.dashboard_tenant, name='tenant_rental_insurance'),
    path('tenant/services', dashboard_views.dashboard_tenant, name='tenant_services'),


    #Tasker
    path('tasker' , dashboard_views.dashboard_tasker, name='dashboard_tasker'),
    path('tasker/manage_schedule' , dashboard_views.dashboard_tasker, name='tasker_manage_schedule'),
    path('tasker/wev_dev' , dashboard_views.dashboard_tasker, name='tasker_web_dev'),


    #RentAnything
    path('rentanything', dashboard_views.dashboard_rentanything, name='dashboard_rentanything'),
    path('rentanything/applications/all', dashboard_views.dashboard_rentanything, name='rentanything_applications'),
    path('rentanything/applications/accepted', dashboard_views.dashboard_rentanything, name='rentanything_applications_accepted'),

    #BuyAndSell
    path('buyandsell', dashboard_views.dashboard_buyandsell, name='dashboard_buyandsell'),
    path('buyandsell/applications/all', dashboard_views.dashboard_buyandsell, name='buyandsell_applications'),
    path('buyandsell/applications/accepted', dashboard_views.dashboard_buyandsell, name='buyandsell_applications_accepted'),

    #DeliverAnything
    path('deliveranything',dashboard_views.dashboard_deliveranything, name='dashboard_deliveranything'),
    path('deliveranything/completed',dashboard_views.dashboard_deliveranything, name='deliveranything_completed'),
    path('deliveranything/jobs', dashboard_views.dashboard_deliveranything, name='deliveranything_jobs'),
    path('deliveranything/jobs/accept/<int:pk>', dashboard_views.accept_job, name='deliveranything_accept'),

    #Chats
    path('chats/' , dashboard_views.chats, name='chats'),
    path('chats/<pk>/' , dashboard_views.chats, name='chats_detail'),

    #Notifications
    path('notifications/', dashboard_views.notifications, name='notifications'),
    path('notifications/<pk>/', dashboard_views.notifications, name='notifications_detail'),

    #Email
    path('email/' , dashboard_views.email, name='email'),

    #Social
    path('social/' , dashboard_views.social, name='social'),

    #Ajax
    path('landlord/select_day/' , dashboard_views.sfv_day_select),
    path('tenant/accept_day/'   , dashboard_views.sfv_day_accept),

    path('landlord/delete/listing/' , dashboard_views.delete_listing),
    path('landlord/tenants/verification/send/' , dashboard_views.tenant_verification),


]

faq/urls.py
from django.urls import path
from .views import FaqListview

urlpatterns = [
    path('', FaqListview.as_view(),name='faq'),
]

dashboards/models.py
from django.db import models
from rentals.models import Landlord
# Create your models here.
#TenantPeriod Yes Tnant
#Booking table might help.
class Calendar(models.Model):
    pass

class TenantVerification(models.Model):
    landlord = models.ForeignKey(Landlord, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=250, default='')
    phone_number = models.CharField(max_length=250, default='')
    address = models.CharField(max_length=250, default='')
    notes = models.CharField(max_length=500, default='')
    verified = models.BooleanField(default=False)
    replied_notes = models.CharField(max_length=500, default='')

leases/models.py
from django.db import models
from accounts.models import User
from django.core.validators import MinValueValidator,MaxValueValidator
from datetime import datetime
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.urls import reverse
import uuid
from io import BytesIO
from os.path import splitext
from django.core.files.base import ContentFile
from PIL import Image as PILImage
from resizeimage import resizeimage
from resizeimage.imageexceptions import ImageSizeError

RENTAL_TYPE = (
    (1,"Using Us"),
    (2,"Other Platform"),
)

CITY_TYPE = (
    (1,'Vancouver'),
    (2,'Toronto'),
    (3,'Seattle'),
    (4,'New York'),
)

def upload_image_path(instance, filename):
    return "listing/{}/{}".format(instance.house.pk, filename)

class HouseManager(models.Manager):
    def short_term_rentals(self):
        return super(HouseManager,self).filter(rented=False,active=True,short_term=True).order_by('-earliest_move_in')

    def active(self):
        return super(HouseManager,self).filter(rented=False,active=True,short_term=False).order_by('-earliest_move_in')
    def inactive(self):
        return super(HouseManager,self).filter(rented=True,active=True,short_term=False).order_by('-earliest_move_in')
        
    def active_by_user(self,user):
        return super(HouseManager,self).filter(user=user,rented=False,active=True).order_by('-earliest_move_in')
    def inactive_by_user(self,user):
        return super(HouseManager,self).filter(user=user,rented=True,active=True).order_by('-earliest_move_in')
    # def applicants(self,slug):
    #     return super(HouseManager,self).filter(slug=slug).applications.all()
    

class House(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=1000)
    duration = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(30)], help_text="Duration for new lease in months")
    earliest_move_in = models.DateField(default=datetime.now)
    latest_move_out = models.DateField(default=datetime.now)
    monthly_rent = models.DecimalField(max_digits=10, decimal_places=2, null=True,help_text="In Cad")
    slug = models.SlugField(max_length=255,unique=True,blank=True)
    uploaded_at = models.DateField(auto_now=True,auto_now_add=False)
    updated_at = models.DateField(auto_now=False,auto_now_add=True)
    rented = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    rental_status = models.IntegerField(choices=RENTAL_TYPE,null=True,blank=True)

    address = models.CharField(max_length=100, null=True)
    zip_code = models.CharField(max_length=10, null=True)
    city = models.IntegerField(choices=CITY_TYPE, null=True,help_text="Currently we are limited to these cities")

    resign = models.BooleanField(default=False,null=True,help_text="When the sublease ends you can sign a new lease directly with the landlord")
    has_dishwasher = models.BooleanField(default=False, null=True)
    pets_allowed = models.BooleanField(default=False, null=True)
    heating = models.BooleanField(default=False, null=True)
    has_closet = models.BooleanField(default=False, null=True)
    is_furnished = models.BooleanField(default=False, null=True)
    is_partially_furnished = models.BooleanField(default=False, null=True)

    external_source = models.BooleanField(default=False,null=True)
    external_link = models.URLField(max_length=200,null=True,blank=True)
    short_term = models.BooleanField(default=False)
    
    favourites = models.ManyToManyField(User,related_name='favourites',blank=True)
    applications = models.ManyToManyField(User,related_name='applications',blank=True)

    objects = HouseManager()

    def __str__(self):
        return self.title

    @property
    def has_amenities(self):
        return self.has_dishwasher or self.pets_allowed or self.heating or self.has_closet or self.is_furnished or self.is_partially_furnished 

    @property
    def get_monthly_rent(self):
        return "$"+str(self.monthly_rent)+"/mo"
    @property
    def get_address(self):
        return self.address+" "+ dict(CITY_TYPE)[self.city] +" "
    
    @property
    def get_gallery(self):
        return Image.objects.filter(house=self.pk)

    @property
    def get_bookings(self):
        return Booking.objects.filter(house=self.pk,accepted=True)
    
    @property
    def get_thumbnail(self):
        cover = self.get_gallery.first()
        try:
            return cover.src.url
        except AttributeError:
            return None
    def get_absolute_url(self):
        return reverse('listing-detail', kwargs={'slug': self.slug})


class Image(models.Model):
    house = models.ForeignKey(House, on_delete=models.CASCADE)
    src = models.ImageField(upload_to=upload_image_path,verbose_name='Image')

    def __str__(self):
        return self.house.title

    def save(self, **kwargs):
        name = uuid.uuid4()
        _, extension = splitext(self.src.name)
        pil_image = PILImage.open(self.src)
        img_format = pil_image.format
        image_io = BytesIO()
        pil_image.save(
            image_io, format=img_format
        )
        try:
            new_image = resizeimage.resize_cover(pil_image, [1000, 1000])
            new_image_io = BytesIO()
            new_image.save(new_image_io, format=img_format)
            self.src.save(
                '%s%s' % (name, extension),
                content=ContentFile(new_image_io.getvalue()),
                save=False
            )
        except ImageSizeError:
            self.src.save(
                '%s%s' % (name, extension),
                content=ContentFile(image_io.getvalue()),
                save=False
            )

        super(Image, self).save(**kwargs)


def create_slug(instance,new_slug = None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = House.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug,qs.first().id)
        return create_slug(instance,new_slug=new_slug)
    return slug

def pre_save_house_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        from memberships.context_processors import get_user_membership
        # if get_user_membership(instance.user) != 'Landlord':
        #     instance.rented = False
        instance.slug = create_slug(instance)
    

pre_save.connect(pre_save_house_receiver,sender=House)


class Lead(models.Model):
    email = models.EmailField()
    phone_number = models.CharField(max_length=13)
    link = models.CharField(max_length=350)

    def __str__(self):
        return self.email


class Booking(models.Model):
    start = models.DateField()
    end = models.DateField()
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    house = models.ForeignKey(House, on_delete=models.CASCADE, related_name='bookings')
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return self.house.title

dashboards/forms.py
from django import forms


class CurrentDashForm(forms.Form):

        FRUIT_CHOICES= [
            ('tasker', 'Tasker'),
            ('landlord', 'Landlord'),
            ('tenant', 'Tenant'),
            ('rentanything', 'Rent Anything'),
            ('buyandsell', 'Buy & Sell'),
            ]
        dashboard_types = forms.CharField(widget=forms.Select(choices=FRUIT_CHOICES))

templates/dashboards/dashboard_main_content/dashboard-content-main.html
{% extends '../dashboard.html' %}
{% load static %}

{% block dashboard_content %}


    <div class="dm-content">

      {% if dashboard_type == 'landlord' %}
          <div style="margin-right:20px;" class='dmc-box'>
              <div class='dmcb-r1'>
                  <div> Long Term Rentals </div>
                  <div>
                      <div>  </div>
                      <div id='dmc_click1'>
                        <img id="dashnavbar3_click" style="display:none" src="{% static 'img/cright.svg' %}">
                        <img id="dashnavbar3_click" src="{% static 'img/cdown.svg' %}">
                      </div>
                  </div>
              </div>

              {% for x in request.user.house_set.all %}
                {% if not x.short_term %}  {% include "dashboards/dashboard_main_content/dmc/landlord_box.html" %}  {% endif %}
              {% endfor %}
          </div>


          <div style="margin-right:20px;" class='dmc-box'>
              <div class='dmcb-r1'>
                  <div> Short Term Rentals </div>
                  <div>
                      <div>  </div>
                      <div id='dmc_click1'>
                        <img id="dashnavbar3_click" style="display:none" src="{% static 'img/cright.svg' %}">
                        <img id="dashnavbar3_click" src="{% static 'img/cdown.svg' %}">
                      </div>
                  </div>
              </div>
              {% for x in request.user.house_set.all %}
                    {% if  x.short_term %}  {% include "dashboards/dashboard_main_content/dmc/landlord_box.html" %}  {% endif %}
              {% endfor %}
          </div>

          <div style="margin-right:20px;" class='dmc-box'>
              <div class='dmcb-r1'>
                  <div> Past Rentals </div>
                  <div>
                      <div>  </div>
                      <div id='dmc_click1'>
                        <img id="dashnavbar3_click" style="display:none" src="{% static 'img/cright.svg' %}">
                        <img id="dashnavbar3_click" src="{% static 'img/cdown.svg' %}">
                      </div>
                  </div>
              </div>

              {% for x in request.user.house_set.all %}
                {% if not x.active %}
                    <div class='dmcb-r2'>
                          <div class='dash-listing-pane'>
                              <div> {{ x.title}} </div>
                              <div> <div> Uploaded at  {{ x.uploaded_at }} </div> </div>
                              <div> {% if x.applications_set.count > 0 %} <div> Applicants  {{ x.applications_set.count  }} </div> {% else %} No Applications {% endif %} </div>
                          </div>
                    </div>
                {% endif %}
              {% endfor %}
          </div>



      {% elif dashboard_type == 'tenant' %}
            <div class='dmc-box'>
              <div class='dmcb-r1'>
                  <div> Applied At </div>
                  <div>
                      <div>  </div>
                      <div id='dmc_click1'>
                        <img id="dashnavbar3_click" style="display:none" src="{% static 'img/cright.svg' %}">
                        <img id="dashnavbar3_click" src="{% static 'img/cdown.svg' %}">
                      </div>
                  </div>
              </div>
            </div>

            <div class='dmc-box'>
              <div class='dmcb-r1'>
                  <div> Tenant On </div>
                  <div>
                      <div>  </div>
                      <div id='dmc_click1'>
                        <img id="dashnavbar3_click" style="display:none" src="{% static 'img/cright.svg' %}">
                        <img id="dashnavbar3_click" src="{% static 'img/cdown.svg' %}">
                      </div>
                  </div>
              </div>
            </div>
      {% elif dashboard_type == 'tasker' %}
        <div class='dmc-box'>
          <div class='dmcb-r1'>
              <div> Tasks </div>
              <div>
                  <div>  </div>
                  <div id='dmc_click1'>
                    <img id="dashnavbar3_click" style="display:none" src="{% static 'img/cright.svg' %}">
                    <img id="dashnavbar3_click" src="{% static 'img/cdown.svg' %}">
                  </div>
              </div>
          </div>


            {% for x in request.user.tasker.task_set.all %}
            <div class='dmcb-r2'>
                  <div class='dash-listing-pane'>
                      <div> {{ x.name }} </div>
                      <div> <div> Due  {{ x.date }} </div> </div>
                      <div> <div> Price {{ x.budget }}   </div> </div>
                  </div>
            </div>
            {% endfor %}
        </div>
      {% endif %}


    </div>
{% endblock %}