businesses/urls.py
from django.urls import path
import businesses.views as views

urlpatterns = [
    path('', views.BusinessIndex.as_view(), name="businesses-home"),
    path('detail/<int:pk>/', views.BusinessDetailView.as_view(), name="business-detail"),
    path('cart/add/', views.cart_add, name="cart-add"),
    path('cart/remove/', views.cart_remove, name="cart-remove"),
    path('cart/create/', views.business_delivery, name="cart-create"),
    path('cart/quote/', views.retail_quote, name="retail-quote"),
    path('payment/add/', views.payment_method, name="card-payment")
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from rentals.sitemaps import HouseSitemap
from services.sitemaps import ServiceSitemap
from django.views.generic import TemplateView


sitemaps = {
    'houses': HouseSitemap,
    'services': ServiceSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('finance/',include('finances.urls')),
    path('rentals/',include('rentals.urls')),
    path('services/',include('services.urls')),
    path('rentanything/', include('rentanything.urls')),
    path('buyandsell/', include('buyandsell.urls')),
    path('deliveranything/', include('deliveranything.urls')),
    path('businesses/', include('businesses.urls')),
    path('faq/',include('faq.urls')),
    path('',include('agreements.urls')),
    path('membership/',include('memberships.urls')),
    path('dashboard/',include('dashboards.urls')),
    path('robots.txt', include('robots.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path
from .views import FaqListview

urlpatterns = [
    path('', FaqListview.as_view(),name='faq'),
]

businesses/models.py
import uuid
from os.path import splitext
from PIL import Image as PILImage
from io import BytesIO

from django.core.files.base import ContentFile
from django.db import models
from django.db.models import Sum
from resizeimage import resizeimage
from resizeimage.imageexceptions import ImageSizeError


def upload_image_path(instance, filename):
    return "businesses/{}/{}".format(instance.store.pk, filename)


class Store(models.Model):
    business = models.OneToOneField('deliveranything.Business', on_delete=models.CASCADE)

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Product(models.Model):
    store = models.ForeignKey('businesses.Store', on_delete=models.CASCADE)

    title = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.CharField(max_length=500)
    image = models.ImageField(upload_to=upload_image_path, verbose_name='Product Image')

    def __str__(self):
        return f"{self.title} at {self.store}"

    def save(self, **kwargs):
        name = uuid.uuid4()
        _, extension = splitext(self.image.name)
        pil_image = PILImage.open(self.image)
        img_format = pil_image.format
        image_io = BytesIO()
        pil_image.save(
            image_io, format=img_format
        )
        try:
            new_image = resizeimage.resize_cover(pil_image, [1000, 1000])
            new_image_io = BytesIO()
            new_image.save(new_image_io, format=img_format)
            self.image.save(
                '%s%s' % (name, extension),
                content=ContentFile(new_image_io.getvalue()),
                save=False
            )
        except ImageSizeError:
            self.image.save(
                '%s%s' % (name, extension),
                content=ContentFile(image_io.getvalue()),
                save=False
            )

        super(Product, self).save(**kwargs)


class Cart(models.Model):
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE, related_name='customer', blank=True, null=True)

    email = models.EmailField(max_length=255, null=True, blank=True)  # Used for Anonymous User

    store = models.ForeignKey('businesses.Store', on_delete=models.CASCADE,  related_name='store')
    products = models.ManyToManyField('businesses.CartProduct', blank=True, related_name='products')

    def __str__(self):
        if self.email:
            return f"{self.email}'s cart at {self.store} (Anonymous User)"
        else:
            return f"{self.user}'s cart at {self.store}"

    @property
    def get_cost(self):
        cost = 0
        for product in self.products.all():
            cost += product.get_cost

        return cost


class CartProduct(models.Model):
    product = models.ForeignKey('businesses.Product', on_delete=models.CASCADE, related_name='product_in_cart')
    cart = models.ForeignKey('businesses.Cart', on_delete=models.CASCADE, related_name='cart_for_product')
    amount = models.IntegerField(null=True)

    def __str__(self):
        return f"{self.amount} of {self.product}"

    @property
    def get_cost(self):
        price = self.product.price
        return round(self.amount * price, 2)

businesses/forms.py
from django import forms
from .models import Store, Product, Cart


class AnonymousCartForm(forms.ModelForm):

    class Meta:
        model = Cart
        fields = ('email',)
        labels = {
            'email': 'Enter Your Email To Start Shopping'
        }


class StoreForm(forms.ModelForm):

    class Meta:
        model = Store
        fields = (
            'name',
            'description',
        )
        labels = {
            'name': 'Store Name',
            'description': 'Brief Store Description'
        }


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = (
            'title',
            'price',
            'description',
            'image'
        )
        labels = {
            'title': 'Product Name',
            'price': 'Product Price',
            'description': 'Brief Description',
        }

businesses/views.py
from datetime import datetime, timedelta

from django.contrib import messages
from django.conf import settings
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView

from deliveranything.models import AnonymousDelivery
from .models import Store, Product, Cart, CartProduct
from .forms import AnonymousCartForm
from config.functions import verify_address
import geopy.distance
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

class BusinessIndex(ListView):
    paginate_by = 25
    model = Store

    def get(self, request, *args, **kwargs):
        stores = Store.objects.all()

        paginator = Paginator(stores, self.paginate_by)

        page = request.GET.get('page')

        try:
            posting_paginations = paginator.page(page)
        except PageNotAnInteger:
            posting_paginations = paginator.page(1)
        except EmptyPage:
            posting_paginations = paginator.page(paginator.num_pages)

        if "q" in request.GET:
            query = request.GET["q"]
            postings = list(Store.objects.filter(
                Q(name__icontains=query) | Q(product__title__icontains=query) | Q(product__description__icontains=query) | Q(description__icontains=query)).distinct())
            paginator = Paginator(postings, self.paginate_by)

            page = request.GET.get('page')

            try:
                posting_paginations = paginator.page(page)
            except PageNotAnInteger:
                posting_paginations = paginator.page(1)
            except EmptyPage:
                posting_paginations = paginator.page(paginator.num_pages)

            return render(request, 'businesses/index.html', {'stores': posting_paginations})

        return render(request, 'businesses/index.html', {'stores': posting_paginations})


class BusinessDetailView(DetailView):
    model = Store
    template_name = "businesses/detail.html"

    def get_context_data(self, **kwargs):
        context = {}
        store = self.get_object()
        context['store'] = store
        if self.request.user.is_authenticated:
            context['cart'] = Cart.objects.get_or_create(user=self.request.user, store=store)[0]
        elif "email" in self.request.GET:
            queryset = Cart.objects.filter(email=self.request.GET['email'], store=store)
            if len(queryset) > 0:
                context['cart'] = queryset.first()

        else:
            context['a_form'] = AnonymousCartForm()

        return context

    def post(self, request, *args, **kwargs):
        form = AnonymousCartForm(request.POST)
        return_url = request.POST.get('next', '/')

        if form.is_valid():
            cart = Cart.objects.get_or_create(email=form.cleaned_data['email'], store=self.get_object())
            if cart[1]:
                messages.success(request, "Session Successfully Created!")
            else:
                messages.success(request, "Previous Session Restored!")

            return HttpResponseRedirect(return_url + f"?email={form.cleaned_data['email']}")

        else:
            messages.warning(request, "Unexpected error. Please try again.")
            return HttpResponseRedirect(return_url)


@csrf_exempt
def payment_method(request):
    context = {}
    if request.is_ajax:
        errors = []
        if request.POST["name"] and request.POST["number"] and request.POST["cvc"] and request.POST["expiry"] and request.POST["quote"] and request.POST["address"]:
            try:
                expiry = request.POST["expiry"].split("/")
                user_card = stripe.PaymentMethod.create(
                    type="card",
                    card={
                        "number": request.POST["number"],
                        "exp_month": int(expiry[0].strip()),
                        "exp_year": int(expiry[1].strip()),
                        "cvc": request.POST["cvc"]
                    }
                )

                if request.POST["coupon"]:
                    list = stripe.PromotionCode.list(code=request.POST['coupon'])['data']
                    if len(list) > 0:
                        off = list[0]["coupon"]["percent_off"]
                        price = float(request.POST['quote'])
                        discount = price * float(off) / 100
                        price = float(request.POST['quote']) - float(discount)
                        context["discount"] = f"Discount of ${discount} off used!"
                    else:
                        price = float(request.POST['quote'])
                else:
                    price = float(request.POST['quote'])

                charge = stripe.PaymentIntent.create(
                    amount=int(float(price) * 100),
                    currency="cad",
                    payment_method=user_card,
                    confirm=True
                )

                description = "Order"
                cart = Cart.objects.get(pk=int(request.POST['cartID']))
                for product in cart.products.all():
                    description += f"\n{product.amount}x {product.product.title} - ${product.get_cost}"

                description += f"\n\nTotal: ${cart.get_cost}"

                delivery = AnonymousDelivery.objects.create(
                    user=cart.email,
                    pickup=cart.store.business.address,
                    dropoff=request.POST["address"],
                    time=datetime.now() + timedelta(hours=4),
                    wait_time="10",
                    description=description,
                    quote=float(request.POST['quote'])
                )

                subject = 'New Delivery Order'
                message = "A new order has been created.\n"
                message += description

                cart.store.business.user.email_user(subject, message, fail_silently=False)

                context["card"] = user_card
            except stripe.error.CardError as e:
                errors.append("Card type not supported or incorrect details.")

                print('Status is: %s' % e.http_status)
                print('Code is: %s' % e.code)
                # param is '' in this case
                print('Param is: %s' % e.param)
                print('Message is: %s' % e.user_message)
            except stripe.error.RateLimitError as e:
                # Too many requests made to the API too quickly
                errors.append("You have sent too many requests too quickly. Try again later.")
            except stripe.error.InvalidRequestError as e:
                # Invalid parameters were supplied to Stripe's API
                print(e.user_message)
                errors.append("An unexpected error occured. Try again.")
            except stripe.error.AuthenticationError as e:
                # Authentication with Stripe's API failed
                # (maybe you changed API keys recently)
                print(e.user_message)
                errors.append("An unexpected error occured. Try again.")
            except stripe.error.APIConnectionError as e:
                # Network communication with Stripe failed
                print(e.user_message)
                errors.append("A network error occured. Try again.")
            except stripe.error.StripeError as e:
                # Display a very generic error to the user
                errors.append("An unexpected error occured. Try again.")
                print('Status is: %s' % e.http_status)
                print('Code is: %s' % e.code)
                # param is '' in this case
                print('Param is: %s' % e.param)
                print('Message is: %s' % e.user_message)

            except Exception as e:
                # Something else happened, completely unrelated to Stripe

                errors.append("An unexpected error occured. Try again.")

                print('Status is: %s' % e.http_status)
                print('Code is: %s' % e.code)
                # param is '' in this case
                print('Param is: %s' % e.param)
                print('Message is: %s' % e.user_message)

        else:
            if not request.POST["quote"]:
                errors.append("Unexpected Error.")
            else:
                errors.append("Please fill all the fields.")

        context["errors"] = errors
        return JsonResponse(context)


@csrf_exempt
def cart_add(request):
    if request.user.is_authenticated and request.is_ajax:
        product = Product.objects.get(pk=request.GET['pk'])
        cart = Cart.objects.get_or_create(user=request.user, store=product.store)[0]
        cart_product = CartProduct.objects.get_or_create(product=product, cart=cart)

        if cart_product[1]:  # If It Was Just Created
            cart_product[0].amount = 1
            cart.products.add(cart_product[0])
        else:
            cart_product[0].amount += 1

        cart_product[0].save()

        return HttpResponse('Complete')
    elif request.is_ajax:
        product = Product.objects.get(pk=request.GET['pk'])
        cart = Cart.objects.get(pk=request.GET['cartID'])
        cart_product = CartProduct.objects.get_or_create(product=product, cart=cart)

        if cart_product[1]:  # If It Was Just Created
            cart_product[0].amount = 1
            cart.products.add(cart_product[0])
        else:
            cart_product[0].amount += 1

        cart_product[0].save()

        return HttpResponse('Complete')


@csrf_exempt
def cart_remove(request):
    if request.user.is_authenticated and request.is_ajax:
        product = Product.objects.get(pk=request.GET['pk'])
        cart = Cart.objects.get_or_create(user=request.user, store=product.store)[0]

templates/businesses/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Business | {{ store.name }}
{% endblock %}

{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-3 mb-5 box-shadow">
        <div class="row">
            <div class="card col-md-12 topborder">
                <div class="row mb4">
                    <div class="col-md-8 col-sm-12">
                        <div class="m-4">
                            <h3 id="storeID" data-id="{{ store.id }}" data-user="{% if user.is_authenticated %}auth{% else %}anon{% endif %}">{{ store.name }}</h3>
                            {{ store.description }}
                        </div>
                        <div class="row m-4">
                            {% for product in store.product_set.all %}
                            <div class="col-md-4 col-sm-12">
                                <div class="card mb-4 shadow-sm topborder">
                                    <img src="{{ product.image.url }}" height="200" alt="Product Picture">
                                    <div class="card-body">
                                        <div class="title"><span class="h5">{{ product.title }}</span> <span class="badge badge-success small float-right">${{ product.price }}</span></div>
                                        <p class="card-text">{{ product.description|truncatewords:12 }}</p>
                                    </div>
                                    {% if cart %}
                                    <div class="card-footer">
                                        <div class="float-right" id="cartButtons">
                                            <i class="fas fa-plus-circle text-success addTo" data-pk="{{ product.pk }}" data-url="{% url 'cart-add' %}"></i> <i class="fas fa-minus-circle text-danger removeFrom" data-pk="{{ product.pk }}" data-url="{% url 'cart-remove' %}"></i>
                                        </div>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-12">
                        <div class="card p-4">
                            <h3 id="storeAddress">{{ store.business.address.get_address }}</h3>
                        </div>
                        <div class="card">
                            <div class="card-body">
                                {% if cart %}
                                <h4 class="text-center" id="cartTitle" data-id="{{ cart.pk }}">Cart</h4>
                                <input class="form-control" type="text" id="couponCode" name="coupon" placeholder="Enter Coupon Code" />
                                {% for product in cart.products.all %}
                                    <div class="text-center mt-2">
                                        {{ product.amount }}x {{ product.product.title }} <span class="badge badge-success">${{ product.get_cost }}</span>
                                        {% if forloop.last %}
                                            <div class="mt-2 mb-2">
                                            <hr>
                                            Total: ${{ cart.get_cost }}
                                            </div>
                                            <button data-toggle="modal" data-target="#addressModal" class="btn btn-success"><i class="fas fa-shopping-cart"></i> Checkout</button>
                                        {% endif %}
                                    </div>
                                {% empty %}
                                    <div class="text-center mt-4" id="cartContent" data-empty="true">Cart Is Empty</div>
                                {% endfor %}
                                {% else %}
                                    <form method="POST" action="{% url 'business-detail' pk=store.id %}">
                                        {% csrf_token %}
                                        <div class="input-group">
                                            <input type="hidden" name="next" value="{{ request.path }}" />

                                            <input type="email" class="form-control" name="{{ a_form.email.html_name }}" id="{{ a_form.email.id_for_label  }}" placeholder="Enter your email to start shopping" aria-label="Enter your email to start shopping" />
                                            <div class="input-group-append">
                                                <button class="btn btn-success" type="submit">
                                                    <i class="fas fa-arrow-right"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-body">
                                {% include "rentals/social_share.html" %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="addressModal" tabindex="-1" role="dialog" aria-labelledby="addressModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form id="addressForm" data-url="{% url 'cart-create' %}">
                    <div class="modal-header">
                        <h5 class="modal-title" id="addressModalLabel">Where do you want the delivery?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div id="messageBox"></div>
                        <div id="paymentDiv"></div>
                        <div id="cardDiv" class="mb-2">
                            <form action="{% url 'user-payment' %}" name="cardform" id="cardID" method="POST">
                          {% csrf_token %}
                            <div class='card-wrapper mb-4'></div>
                            <script src="{% static 'js/card.js' %}"></script>
                            <div class="row">
                                <div class="col-md-8">
                                    <label>Credit Card Number </label>
                                    <input type="text" class="form-control" id="number" name="number" />
                                </div>
                                <div class="col-md-4">
                                    <label>Expiration</label>
                                    <input type="text" class="form-control" id="exp" placeholder="MM/YY" name="expiry"/>
                                </div>
                                <div class="col-md-8">
                                    <label>Name</label>
                                    <input type="text" class="form-control" id="name" name="name" />
                                </div>
                                <div class="col-md-4">
                                    <label>CVV/CVC </label>
                                    <input type="text" class="form-control" id="cvc" name="cvc" />
                                </div>
                            </div>
                        </form>
                        </div>
                        <div id="formDiv">
                            <div class="form-group">
                                <label for="inputAddress">Address</label>
                                <input type="text" class="form-control" id="inputAddress" required>
                            </div>
                            <div class="form-group">
                                <label for="inputAddress2">Address Line 2</label>
                                <input type="text" class="form-control" id="inputAddress2">
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="inputCity">City</label>
                                    <input type="text" class="form-control" id="inputCity" required>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="inputProvince">Province</label>
                                    <input type="text" class="form-control" id="inputProvince" value="BC" disabled>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="inputPostal">Postal Code</label>
                                    <input type="text" class="form-control" id="inputPostal" required>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal" id="closeBtn" data-url="{% url 'payment-methods' %}" data-accept="{% url 'ajax-accept' %}" data-payment="{% url 'user-payment' %}" data-final="{% url 'deliver-payment' %}">Close</button>
                            <button type="submit" class="btn btn-success" id="quoteSubmit" data-url="{% url 'retail-quote' %}">Submit</button>
                            <button type="submit" class="btn btn-success" id="payBtn" data-url="{% url 'card-payment' %}"><i class="fas fa-credit-card"></i> Pay</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block js %}
<script src="{% static 'js/businesses.js' %}"></script>
    <script>

    var card = new Card({
    // a selector or DOM element for the form where users will
    // be entering their information
    form: 'form', // *required*
    // a selector or DOM element for the container
    // where you want the card to appear
    container: '.card-wrapper', // *required*

    formSelectors: {
        numberInput: 'input[name="number"]', // optional — default input[name="number"]
        expiryInput: 'input[name="expiry"]', // optional — default input[name="expiry"]
        cvcInput: 'input[name="cvc"]', // optional — default input[name="cvc"]
        nameInput: 'input[name="name"]' // optional - defaults input[name="name"]
    },

    // Strings for translation - optional
    messages: {
        validDate: 'valid\ndate', // optional - default 'valid\nthru'
        monthYear: 'mm/yyyy', // optional - default 'month/year'
    },

    // Default placeholders for rendered fields - optional
    placeholders: {
        number: '•••• •••• •••• ••••',
        name: 'Full Name',
        expiry: '••/••',
        cvc: '•••'
    },

    // if true, will log helpful messages for setting up Card
    debug: false // optional - default false
});

    </script>
{% endblock js %}

templates/businesses/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Incuman - The Digital Marketplace
{% endblock %}

{% block content %}
<section class="jumbotron text-center m-0">
  <div class="container">
      <h1>Businesses</h1>
  </div>
</section>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row justify-content-center ma4">
        {% include "includes/search.html" %}
    </div>
    <div class="row">
        <div class="card" style="width: 100%;">
            <div class="card-body topborder">
                <ul class="list-group list-group-flush">
                    {% for store in stores %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-6 col-md-4">
                                <div class="ma4"><h3><a href="{% url 'business-detail' pk=store.pk %}" class="text-dark">{{ store.name }}</a></h3></div>
                                <h6 class="ma4 text-muted">{{ store.description }}</h6>
                            </div>
                            <div class="col-12 col-md-8">
                                <div class="col" style="margin-left: 80%;">
                                    <div class="row ma4">
                                        <a class="btn btn-success" style="color: white;" href="{% url 'business-detail' pk=store.pk %}">
                                            <b>See Listing</b>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <hr>
            {% if stores.has_other_pages %}
              <ul class="pagination ml-4">
                {% if stores.has_previous %}
                  <li class="page-item"><a class="page-link" href="?page={{ stores.previous_page_number }}">&laquo;</a></li>
                {% else %}
                  <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
                {% endif %}
                {% for i in stores.paginator.page_range %}
                  {% if stores.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                  {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if stores.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{ stores.next_page_number }}">&raquo;</a></li>
                {% else %}
                  <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
                {% endif %}
              </ul>
            {% endif %}
        </div>
    </div>
  </div>
</div>
{% endblock %}